version: "3.9"
services:
  etcd:
    image: quay.io/coreos/etcd:v3.4.15
    networks:
      default:
        ipv4_address: 192.168.100.1
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - ./etcd:/etcd-data
    command:
      /usr/local/bin/etcd
      --data-dir=/etcd-data
      --name node1
      --initial-advertise-peer-urls http://192.168.100.1:2380
      --listen-peer-urls http://0.0.0.0:2380
      --advertise-client-urls http://192.168.100.1:2379
      --listen-client-urls http://0.0.0.0:2379
      --initial-cluster node1=http://192.168.100.1:2380
  api-server:
    image:  gcr.io/google-containers/kube-apiserver-amd64:v1.18.6
    networks:
      default:
        ipv4_address: 192.168.101.1
    ports:
      - "64443:6443"
      - "8080:8080"
    command: 
      kube-apiserver
      --etcd-servers http://192.168.100.1:2379
      --insecure-bind-address 0.0.0.0
      --insecure-port 8080
  kube-controller-manager:
    image:  gcr.io/google-containers/kube-controller-manager:v1.18.6
    networks:
      default:
        ipv4_address: 192.168.102.1
    command:
      kube-controller-manager --master http://192.168.101.1:8080
  kube-scheduler:
    image: gcr.io/google-containers/kube-scheduler:v1.18.6
    networks:
      default:
        ipv4_address: 192.168.102.2
    command:
      kube-scheduler --master http://192.168.101.1:8080
networks:
  default:
    name: kubernetes-hardway
    ipam:
      driver: default
      config:
          - subnet: 192.168.100.0/16