apiVersion: v1
kind: Config
preferences: {}
current-context: local
clusters:
  - name: default
    cluster:
      server: 'http://192.168.101.1:8080'
      insecure-skip-tls-verify: true
contexts:
  - name: local
    context:
      cluster: default
      user: default
users:
  - name: default
    user:
      username: admin
      password: useless-password
